---
name: Linux

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CCACHE_VERSION: 4.8.3
  CCACHE_BASEDIR: ${{ github.workspace }}
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_COMPRESS: true
  CCACHE_COMPRESSLEVEL: 6
  CCACHE_MAXSIZE: 1000M
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Caching CPM CMake dependencies
        uses: tespkg/actions-cache@v1
        with:
          path: '**/cpm_modules'
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
          accessKey: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secretKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          endpoint: ${{ secrets.AWS_ENDPOINT }}

      - name: Update dependencies for JUCE
        run: |
          sudo apt update
          sudo apt install libasound2-dev libjack-jackd2-dev \
              ladspa-sdk \
              libfreetype6-dev \
              libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev \
              libwebkit2gtk-4.0-dev \
              libglu1-mesa-dev mesa-common-dev \
              ccache \
              ninja-build

      - name: ccache cache files
        id: ccache_cache
        uses: tespkg/actions-cache@v1
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-ccache-
          bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
          accessKey: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secretKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          endpoint: ${{ secrets.AWS_ENDPOINT }}

      - name: Show ccache stats
        run: |
          ccache -s

      - name: Configure
        run: |
          cmake -B build -G Ninja -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Debug -DBOOST_UT_ENABLE_RUN_AFTER_BUILD=NO -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: |
          cmake --build build

      - name: Test
        run: |
          ctest --test-dir build
