---
name: MacOS

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  SCCACHE_VERSION: 0.6.0
  SCCACHE_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
  SCCACHE_REGION: auto
  SCCACHE_GHA_ENABLED: true
  SCCACHE_CACHE_TYPE: S3
  SCCACHE_LOG: debug
  SCCACHE_NO_DAEMON: 1
  SCCACHE_ENDPOINT: https://${{ secrets.AWS_ENDPOINT }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Caching CPM CMake dependencies
        uses: tespkg/actions-cache@v1
        with:
          path: '**/cpm_modules'
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
          accessKey: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secretKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          endpoint: ${{ secrets.AWS_ENDPOINT }}

      - name: Install ninja and python
        run: brew install llvm ninja

      - name: Install sccache
        run: |
          wget https://github.com/mozilla/sccache/releases/download/v${{ env.SCCACHE_VERSION }}/sccache-v${{ env.SCCACHE_VERSION }}-x86_64-apple-darwin.tar.gz
          tar -xvf sccache-v${{ env.SCCACHE_VERSION }}-x86_64-apple-darwin.tar.gz
          echo "$PWD/sccache-v${{ env.SCCACHE_VERSION }}-x86_64-apple-darwin" >> $GITHUB_PATH

      - name: configure
        run: |
          cmake -B build -G Ninja -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Debug -DBOOST_UT_ENABLE_RUN_AFTER_BUILD=NO -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: build
        run: |
          cmake --build build

      - name: Test
        run: |
          ctest --test-dir build

      - name: Show ccache stats
        run: |
          ccache -s -v
