---
name: Windows

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  SCCACHE_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
  SCCACHE_ENDPOINT: https://${{ secrets.AWS_ENDPOINT }}
  SCCACHE_REGION: auto
  SCCACHE_GHA_ENABLED: true
  SCCACHE_LOG: debug
  SCCACHE_NO_DAEMON: 1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        toolset: [ClangCl, v143]
        std: [17, 20]
        exclude:
          - toolset: v143
            std: 17

    steps:
      - uses: actions/checkout@v3

      - name: Caching CPM CMake dependencies
        uses: tespkg/actions-cache@v1
        with:
          path: '**/cpm_modules'
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
          accessKey: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secretKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          endpoint: ${{ secrets.AWS_ENDPOINT }}

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: configure
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DBOOST_UT_ENABLE_RUN_AFTER_BUILD=NO -DBOOST_UT_DISABLE_MODULE=ON -G "Visual Studio 17 2022" -T ${{matrix.toolset}} -DCMAKE_CXX_STANDARD:STRING=${{matrix.std}} -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache

      - name: build
        run: cmake --build build

      - name: Test
        run: |
          ctest --test-dir build -C Debug
